/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void yesButton_clicked(GButton source, GEvent event) { //_CODE_:yesButton:966810:
  //println("button1 - GButton >> GEvent." + event + " @ " + millis());
  changeQ = true; //Question can be changed
  newQ= true; //New question is supposed to be shown
  questionBack = true; //Allow the user to use the back button
  answerGiven = "yes";
  //animalRemove();
} //_CODE_:yesButton:966810:

public void noButton_clicked(GButton source, GEvent event) { //_CODE_:noButton:529912:
  //println("button2 - GButton >> GEvent." + event + " @ " + millis());
  changeQ = true; //Question can be changed
  newQ=true; //New question is supposed to be shown
  questionBack = true; //Allow the user to use the back button
  answerGiven = "no";
  //animalRemove();

} //_CODE_:noButton:529912:

public void resetButton_clicked(GImageButton source, GEvent event) { //_CODE_:resetButton:408963:
  //println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
  gameStart = false;
  
  yesButton.setVisible(false);
  noButton.setVisible(false);
  resetButton.setVisible(false);
  
  questionsAsked.clear();
  changeQ = true;
  newQ = true;
  questionBack = true;
  answerGiven = "none";
  setup();
} //_CODE_:resetButton:408963:

public void startButton_clicked(GButton source, GEvent event) { //_CODE_:startButton:995690:
  //println("startButton - GButton >> GEvent." + event + " @ " + millis());
  gameStart = true;
} //_CODE_:startButton:995690:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:678080:
  appc.background(230);
} //_CODE_:window1:678080:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  yesButton = new GButton(this, 186, 431, 129, 67);
  yesButton.setText("Yes");
  yesButton.setTextBold();
  yesButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  yesButton.addEventHandler(this, "yesButton_clicked");
  noButton = new GButton(this, 465, 427, 129, 67);
  noButton.setText("No");
  noButton.setTextBold();
  noButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  noButton.addEventHandler(this, "noButton_clicked");
  resetButton = new GImageButton(this, 745, 15, 41, 41, new String[] { "resetbutton.jpg" } );
  resetButton.addEventHandler(this, "resetButton_clicked");
  startButton = new GButton(this, 344, 301, 129, 67);
  startButton.setText("Start");
  startButton.setTextBold();
  startButton.addEventHandler(this, "startButton_clicked");
  window1 = GWindow.getWindow(this, "Animals to choose from", 0, 0, 200, 650, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 40, -20, 120, 200);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Choose an animal from this list, and I will guess which one it is. Press start when you're ready!");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 40, 100, 120, 530);
  label2.setText(getAnimalNames());
  label2.setOpaque(false);
  //label3 = new GLabel(window1, 561, 42, 61, 488);
  //label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  //label3.setText("abc");
  //label3.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton yesButton; 
GButton noButton; 
GImageButton resetButton; 
GButton startButton; 
GWindow window1;
GLabel label1; 
GLabel label2; 
//GLabel label3;
